version: '2'

services:
  mysql:
    image: mysql:5.7
    networks:
      database:
        aliases: 
          - db
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  
  redis:
    image: redis:4
    networks:
      cache:

  magento:
    build:
      context: ./magento
      args:
        - COMPOSER_AUTH
        - MAGENTO_VERSION
    volumes:
      - magento-data:/app
  
  php-fpm:
    build: ./php-fpm
    user: "1000:1000"
    depends_on: 
      - magento
    networks:
      backend:
      cache:
      database:
    volumes:
      - magento-data:/app
  
  nginx:
    image: nginx
    depends_on:
      - magento
    ports:
      - "80:80"
    networks:
      frontend:
      backend:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - magento-data:/app

networks:
  backend:
  database:
  cache:
  frontend:

volumes:
  magento-data:
